const bookTypes = [
  "Fiction",
  "Non-Fiction",
  "Science Fiction",
  "Mystery",
  "Fantasy",
  "Biography",
  "Autobiography",
  "History",
  "Language",
  "Science",
  "Mathematics",
  "Computer Science",
  "Political Science",
  "Philosophy",
  "Art",
  "Music",
  "Graphic Novels",
  "Self-Help",
  "Cooking",
  "Travel",
  "Poetry",
  "Religion",
  "Research Paper",
  "Health",
  "Children's Books",
  "Reference",
];
const pages = [
  "HomePage",
  "StudentPage",
  "TeacherPage",
  "BookPage",
  "AdminPage",
  "NotificationPage",
  "SettingsPage",
  "DocsPage",
  "BackupPage",
  "HelpPage"
];